- name: a simple rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  
  rules:
    - name: launch_job_on_webhook
      condition: event.payload.command == "restart"
      action:
        run_job_template:
          name: "eda-student01"
          organization: "student_org"
          job_args:
            extra_vars:
              trigger_reason: "{{ event.payload.reason | default('no reason provided') }}"
